apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: infra-tools   # де встановлено ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/Tati-Sky/goit-argo
    path: namespaces/application
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
